### ISSUE TITLE
www.tagesanzeiger.ch

### ISSUE THREAD

**Issue by thommmmmy** [Draluy/cookienotificationhider#38]
Still see cookie pup up on https://www.tagesanzeiger.ch/

**Comment by Draluy** [comment]
I dont see a cookie pop up but a pop up to signup for a free trial (which I'm not blocking to keep this addon focused). Can you provide a screenshot?

If its this popup, I'm not blocking it, as it could be useful for some people.
![image](https://user-images.githubusercontent.com/8559173/106499698-2f4d6880-64c1-11eb-9c56-b2eef8cf6ce8.png)

Leaving open for now.

**Comment by Draluy** [comment]
@thommmmmy ?

**Comment by thommmmmy** [comment]
Yes, this pupup.
