### ISSUE TITLE
singe in pupup on www.youtube.com 

### ISSUE THREAD

**Issue by thommmmmy** [Draluy/cookienotificationhider#39]
Please hide the singe in pupup on https://www.youtube.com/ .
I haven't got a youtube account and I'm annoying of cklicking "no tanks".

**Comment by Draluy** [comment]
The sign-in popus are not in the scope of this addon, but im making an exception for this popup, as its really stupid and provides no value.

**Comment by thommmmmy** [comment]
Tank you very much!
