### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by thommmmmy** [Draluy/cookienotificationhider#40]
A really heavy used service: https://www.google.ch/maps isn't filtered.

Pleas remove the cookie notice on all Google Services. 

If this Plugin likes  to become  the standard for blocking cookie notices, it needs to filter all Google services by default. This is some kind of compulsory. If smaller pages aren't blacken, isn't a big matter. But Google is really one of the showcase for such a Plugin. 

I hope you understand my thought.

**Comment by Draluy** [comment]
Should be ok, please tell me if it works (wait for addon to update to version 1.0.29)

**Comment by thommmmmy** [comment]
Seams to work well, thank you!

**Comment by thommmmmy** [comment]
Again, G-Maps isn't filtered!
