### ISSUE TITLE
YouTube pop-ups not showing

### ISSUE THREAD

**Issue by jakeafoster** [Draluy/cookienotificationhider#42]
Hi there,

I noticed pop-ups on YouTube were not showing and because of this, functionality such as adding videos to a playlist and changing account were not possible. I traced the issue to this extension.

I believe the issue stems from b1e2f8d, and this line specifically: https://github.com/Draluy/cookienotificationhider/blob/b1e2f8d9e7e12d9ba03870807a124051e1eed2d7/hiders/HiderRepository.js#L532

**Comment by Draluy** [comment]
Thx for the report, I'll fix this today and release a new version.

**Comment by Draluy** [comment]
I removed the offending line and updated the plugin. Out of curiosity, how did you manage to find the cause of the problem?
It might help me debug other issues :)

**Comment by jakeafoster** [comment]
Thanks for the fix! I confirm YouTube is working now. 👍

I knew that YouTube worked previously with this extension, so I looked at recent commits to see what could have broken it and that line was the only possibility.
