### ISSUE TITLE
Google Pages aren't filtered again

### ISSUE THREAD

**Issue by thommmmmy** [Draluy/cookienotificationhider#43]
Google Pages aren't filtered again. 

If this Plugin likes to become the standard for blocking cookie notices, it needs to filter all Google services by default. This is some kind of compulsory. If smaller pages aren't blacken, isn't a big matter. But Google is really one of the showcase for such a Plugin.

I hope you understand my thought.

**Comment by Draluy** [comment]
Yeah, Google has changed the way it displays cookie info AND displays it several seconds after page load AND does so in a container that is shared with other data, like menus, which makes it a complete pain in the ass to filter now.

**Comment by thommmmmy** [comment]
Well... It was very obvious, that companies will make it harder to filter, sooner or later. If you are unable to "backfire", this plugin is already dead. Sad. Very sad. 

All ad-blockers solve the issue with the changing techniques of the ad-industries. Many of them do very well. Filtering cookie notifications seams to me very similar. 

If Google isn't filtered effectively, this plugin is almost useless. I'll test for an other month. May you find a solution. If Google won't be filtered, I'll reinstall this plugin.

**Comment by Draluy** [comment]
I tried something I'm not sure will work for everybody on version 1.0.34 (please make sure your plugin has updated). Could you tell me if it works for you?
