### ISSUE TITLE
Difference with i-dont-care-about-cookies addon ?

### ISSUE THREAD

**Issue by Peuj** [Draluy/cookienotificationhider#9]
Hi,

Just curious, there is already an extension that seems to do the same job https://addons.mozilla.org/en-US/firefox/addon/i-dont-care-about-cookies/.

Is there a reason you propose your addon ? performance, limitation,.. or just for fun :)

**Comment by Draluy** [comment]
Hi, 

This is why: 
By using it, you explicitly allow websites to do whatever they want with cookies they set on your computer (which they mostly do anyway, whether 

My extension does not allow websites to store cookies.

Cheers,

David

On November 26, 2019 3:32:01 PM GMT+01:00, Peuj <notifications@github.com> wrote:
>Hi,
>
>Just curious, there is already an extension that seems to do the same
>job
>https://addons.mozilla.org/en-US/firefox/addon/i-dont-care-about-cookies/.
>
>Is there a reason you propose your addon ? performance, limitation,..
>or just for fun :) 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Draluy/cookienotificationhider/issues/9

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Peuj** [comment]
Ok thanks.
You should add this in the description, the behavior is interesting and not obvious (based on the name).

(Note that I think that i-dont-care-about-cookies/ can also block cookie.)
